# Generated by Django 6.0 on 2025-12-04 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncIA', '0002_comentario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='denuncias_fotos/'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='status',
            field=models.CharField(choices=[('Em análise', 'Em análise'), ('Resolvido', 'Resolvido'), ('Rejeitado', 'Rejeitado')], default='Em análise', max_length=20),
        ),
        migrations.CreateModel(
            name='GestorPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cra_de_gestor', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
