# Generated by Django 4.2.27 on 2025-12-05 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('denuncIA', '0003_denuncia_foto_alter_denuncia_status_gestorpublico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestorpublico',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_gestor', to=settings.AUTH_USER_MODEL),
        ),
    ]
